apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-api #ClusterRoleBinding的名字
subjects:
  - kind: ServiceAccount
    name: test-api #serviceaccount资源对象的name
    namespace: test-api #serviceaccount的namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin #k8s集群中最高权限的角色
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-api # ServiceAccount的名字
  namespace: test-api # serviceaccount的namespace

